# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' @title rgt - random genotypes
#' @description
#' Generate a matrix of random genotypes.
#' @name rgt
#' 
#' @param nsamp number of samples (columns) to simulate
#' @param nvar number of variants (rows) to simulate
#' @param pphased probability each genotype will be phased
#' @param pploid probability each genotype will be a ploidy level
#' @param pallele probability of each allele
#' 
#' 
#' @details
#' The function \code{rgt} generates a matrix of random genotypes.
#' The parameter `nsamp` determines the number of samples (columns) to simulate.
#' The parameter `nvar` determines the number of variants (rows) to simulate.
#' 
#' @return
#' A matrix with samples in columns and variants in rows.
#' 
#'
#' @export
rgt <- function(nsamp = 4L, nvar = 3L, pphased = as.numeric( c(0.5)), pploid = as.numeric( c(0,1)), pallele = as.numeric( c(0.5,0.5))) {
    .Call('_GeneticDiff_rgt', PACKAGE = 'GeneticDiff', nsamp, nvar, pphased, pploid, pallele)
}

