# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'
#' @title rgt
#' @description
#' Generate a matrix of random genotypes.
#' 
#' @param nsamp number of samples to simulate
#' @param nvar number of variants to simulate
#' @param pphased probability each genotype will be phased
#' @param pploid probability each genotype will be a ploidy level
#' @param pallele probability of each allele
#' 
#' 
#' @details
#' Generate a matrix of random genotypes.
#' 
#' @examples
#' rgt()
#' 
#'
#' @export
rgt <- function(nsamp = 4L, nvar = 3L, pphased = 50L, pploid = as.integer( c(0,100)), pallele = as.integer( c(50,50))) {
    .Call('GeneticDiff_rgt', PACKAGE = 'GeneticDiff', nsamp, nvar, pphased, pploid, pallele)
}

